name: Tests applies and releases new version

on:
  push:
    branches: [acc]

jobs:
  # Merges acc into master and release new tag for the module because a change to Terraform code has been made.
  terraform-module-change:
    uses: guidion-digital/release-workflows/.github/workflows/github-merge-into-master.yaml@v2
    with:
      branch: ${{ github.ref_name }}
    permissions:
      contents: write

  release-module-version:
    needs: [terraform-module-change]
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag.yaml@v2
    with:
      branch: ${{ github.ref_name }}
    permissions:
      contents: write
